development:
  api_root: http://stg-api.akerun.com

test:

staging1:
  api_root: https://api.akerun.com

production:
  api_root: https://api.akerun.com


api:
  login:
    method: "POST"
    path: "/v1/login/"

  logout:
    method: "GET"
    path: "/v1/logout/"

  validate_access_token:
    method: "POST"
    path: "/v1/validate_access_token"

  introduce_email: # Akerun導入メール文言取得API
    method: "POST"
    path: "/v1/bookings"

  hotels:
    method: "GET"
    path: "/v1/hotels"

  hotel_akeruns:
    method: "GET"
    path: "/v1/hotels/:hotel_id/akeruns"

  booking_complete:
    method: "POST"
    path: "/v1/bookings/complete"

  grant: # 鍵付与
    method: "POST"
    path: "/v1/keys"
    defaults:
      key_type: 1 # temporary
      role: 2 # guest

  update: # 鍵更新
    method: "PUT"
    path: "/v1/keys/:id"

  revoke: # 鍵剥奪
    method: "DELETE"
    path: "/v1/keys/:id"
